version: "3.7"
services:
    transmission:
        image: haugene/transmission-openvpn:latest
        container_name: transmission
        cap_add:
            - NET_ADMIN
        devices:
            - /dev/net/tun
        restart: always
        ports:
            - 9091:9091
            - 8888:8888
        dns:
            - 46.227.67.134
            - 192.165.9.158
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - Media:/data
        environment:
            - OPENVPN_PROVIDER=<VPN-provider>
            - OPENVPN_USERNAME=<username>
            - OPENVPN_PASSWORD=<password>
            - LOCAL_NETWORK=<local network ie. 192.168.1.0/16>

    proxy:
        image: haugene/transmission-openvpn-proxy:latest
        container_name: transmission_proxy
        links:
            - transmission
        ports:
            - 8800:8080
        volumes:
            - /etc/localtime:/etc/localtime:ro


    nzbget:
        image: linuxserver/nzbget
        container_name: nzbget
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Stockholm
        volumes:
            - ./appdata/nzbget:/config
            - Media:/media
        ports:
            - 8082:6789
        cap_add:
            - NET_ADMIN
        restart: unless-stopped

    sonarr:
        image: linuxserver/sonarr:preview
        container_name: sonarr
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Stockholm
        volumes:
            - ./appdata/sonarr:/config
            - Media:/media
        restart: unless-stopped
        ports:
            - 8080:8989

    couchpotato:
        image: linuxserver/couchpotato
        container_name: couchpotato
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Stockholm
            - UMASK_SET=022
        volumes:
            - ./appdata/couchpotato:/config
            - Media:/media
        ports:
            - 5050:5050
        restart: unless-stopped

    muximux:
        image: linuxserver/muximux
        container_name: muximux
        environment:
            - PUID=1000
            - PGID=1000
            - TZ="${VPN_TZ}"
        volumes:
            - ./appdata/muximux:/config
        restart: unless-stopped
        ports:
            - 80:80

    watchtower:
        image: containrrr/watchtower
        container_name: watchtower
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        command: --interval 30

volumes:
  Media:
    driver_opts:
      type: "nfs"
      o: "addr=192.10.1.10,rw,soft"
      device: ":/mnt/storage/"