#Media docker-compose made by me Ratnose with the help of Ixnye at Reddit.
#This is version 2.
version: "3.7"
services:
    vpn:
        image: bubuntux/nordvpn
        container_name: nordvpn
        cap_add:
        - net_admin
        devices:
        - /dev/net/tun
        init: true
        environment:
            - USER="${VPNUSER}"
            - PASS="${VPNPASS}"
            - COUNTRY="${VPNCOUNTRY}"
            - PROTOCOL="${VPNPROTOCOL}"
            - CATEGORY="${VPNCATEGORY}"
            - NETWORK="${VPNNETWORKLAN}"
            - OPENVPN_OPTS="${VPNOPENVPN_OPTS}"
            - TZ="${VPN_TZ}"
        ports:
            - 8080:80               #muximux
            - 8989:8989             #Sonarr
            - 7878:7878             #Radarr
            - 6789:6789             #Nzbget
            - 9091:9091             #transmiosson
            - 3579:3579             #Ombi
            - 51413:51413           #transmiosson
            - 51413/udp:51413/udp   #transmiosson
        restart: always

    sonarr:
        image: linuxserver/sonarr:preview
        container_name: sonarr
        environment:
            - PUID=1000
            - PGID=1000
            - TZ="${VPN_TZ}"
        volumes:
            - ./appdata/sonarr:/config
            - Series:/tv
            - Downloads/:/downloads
        restart: unless-stopped
        network_mode: "service:vpn"
        depends_on:
            - vpn

    radarr:
        image: linuxserver/radarr
        container_name: radarr
        environment:
            - PUID=1000
            - PGID=1000
            - TZ="${VPN_TZ}"
        volumes:
            - ./appdata/radarr:/config
            - Movies:/movies
            - Downloads/:/downloads
        restart: unless-stopped
        network_mode: "service:vpn"
        depends_on:
            - vpn

    nzbget:
        image: linuxserver/nzbget
        container_name: nzbget
        environment:
            - PUID=1000
            - PGID=1000
            - TZ="${VPN_TZ}"
        volumes:
            - ./appdata/nzbget:/config
            - Downloads/:/downloads
            - Movies/:/media/movies
        restart: unless-stopped
        network_mode: "service:vpn"
        depends_on:
            - vpn

    transmission:
        image: linuxserver/transmission
        container_name: transmission
        environment:
            - PUID=1000
            - PGID=1000
            - TZ="${VPN_TZ}"
        volumes:
            - ./appdata/transmisson:/config
            - Downloads:/downloads
        restart: unless-stopped
        network_mode: "service:vpn"
        depends_on:
            - vpn

    muximux:
        image: linuxserver/muximux
        container_name: muximux
        environment:
            - PUID=1000
            - PGID=1000
            - TZ="${VPN_TZ}"
        volumes:
            - ./appdata/muximux:/config
        restart: unless-stopped
        network_mode: "service:vpn"
        depends_on:
            - vpn

    watchtower:
        image: containrrr/watchtower
        container_name: watchtower
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        command: --interval 30

    ombi:
        image: linuxserver/ombi
        container_name: ombi
        environment:
            - PUID=1000
            - PGID=1000
            - TZ="${VPN_TZ}"
        volumes:
            - ./appdata/ombi:/config
        restart: unless-stopped
        network_mode: "service:vpn"
        depends_on:
            - vpn

volumes:
  Downloads:
    driver_opts:
      type: "nfs"
      o: "addr=<nfs-server-ip>,rw,soft"
      device: ":/mnt/storage/downloads"

  Movies:
    driver_opts:
      type: "nfs"
      o: "addr=<nfs-server-ip>,rw,soft"
      device: ":/mnt/storage/movies"

  Movies4K:
    driver_opts:
      type: "nfs"
      o: "addr=<nfs-server-ip>,rw,soft"
      device: ":/mnt/storage/movies4k"

  Series:
    driver_opts:
      type: "nfs"
      o: "addr=<nfs-server-ip>,rw,soft"
      device: ":/mnt/storage/series"
